# Generated by Django 3.0.5 on 2020-06-30 12:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0002_diary'),
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Номер робота')),
                ('record', models.TextField(verbose_name='Значения')),
                ('date_create', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
