# Generated by Django 3.0.5 on 2020-06-30 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0003_record'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='record',
        ),
        migrations.AddField(
            model_name='record',
            name='ip',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='record',
            name='mass',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='record',
            name='quality',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='record',
            name='temp',
            field=models.FloatField(default=0),
        ),
    ]
