# Generated by Django 3.0.5 on 2020-07-30 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0004_auto_20200630_1610'),
    ]

    operations = [
        migrations.AddField(
            model_name='diary',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
